Implement Fake Handshaker (1)
matthewstevenson88/grpc-java pull request #4
Opened 2020-08-11 17:22 UTC by davisgu

Implement Fake Handshaker -- I have no idea what "update README" commit is considered a change since master already is up to date with that commit?

2020-08-11 18:07 UTC, matthewstevenson88 requested changes
Thanks for the PR Davis! I've left some comments.

> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-:-METh0-c-pWKl1SQQQ11:bm82a28)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @davisgu and @matthewstevenson88)

___
*[examples/example-tls/README.md, line 64 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METgxLF4kPRuVMcjG0w:-METgsaH9W6XTcobzb0U:b-ronya8) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/README.md#L64)):*
> ```Markdown
> ```
> 
> #### Hello world example with S2A 
> ```

Why are these changes part of this PR? They seem unrelated.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 44 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METbPM7CJnvXhbp7lIn:-METbPM7CJnvXhbp7lIo:b-8tbzx6) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L44)):*
> ```Java
> 
> /**
>  * Server that manages startup/shutdown of a Greeter  server with TLS 1.3 enabled.
> ```

Please change this comment, since we are no longer using a Greeter server.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 60 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METgZN741sUe_AwrrAF:-METgZN741sUe_AwrrAG:b-oox8q6) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L60)):*
> ```Java
>                 .build()
>                 .start();
> ```

Please remove the extra space.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 61 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METgTTZAVjM3FrF_edk:-METgTTZAVjM3FrF_edl:b-lydb9j) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L61)):*
> ```Java
>                 .start();
> 
>         logger.info("Server started, listening at address " + "localhost:"+ port);
> ```

Please remove the " + " between "address" and "localhost".
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 80 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METgcXWAik_HMXihqg3:-METgcXWAik_HMXihqg4:bcs7u6e) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L80)):*
> ```Java
> 
>     /**
>      * Awaits termination on the main thread since the grpc library uses daemon threads.
> ```

Please remove this comment.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 92 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METgjQR5stEEV6q-nTN:-METgjQR5stEEV6q-nTO:bm30qch) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L92)):*
> ```Java
>      *
>      * args:
>      * @param arg[0] contains the server port
> ```

Please add a period at the end of this sentence.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 109 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METc-kMEarohbV8owyb:-METc-kMEarohbV8owyc:bvlizxe) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L109)):*
> ```Java
>     }
> 
>     private static class HandshakerImpl extends S2AServiceGrpc.S2AServiceImplBase {
> ```

Instead of `HandshakerImpl`, can we call it `FakeS2AImpl`?


<!-- Sent from Reviewable.io -->

2020-08-17 22:12 UTC, davisgu reviewed
> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @matthewstevenson88)

___
*[examples/example-tls/README.md, line 64 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METgxLF4kPRuVMcjG0w:-MEySmLHDtUm8LZmA7yo:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/README.md#L64)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Why are these changes part of this PR? They seem unrelated.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 44 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METbPM7CJnvXhbp7lIn:-METmzia7FNAw-rPM8b1:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L44)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please change this comment, since we are no longer using a Greeter server.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 60 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METgZN741sUe_AwrrAF:-METlXPs9eu0KLRvGh-j:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L60)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please remove the extra space.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 61 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METgTTZAVjM3FrF_edk:-METla7jEawyVVwRdicR:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L61)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please remove the " + " between "address" and "localhost".
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 80 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METgcXWAik_HMXihqg3:-METlcWn-inn40hUCF1D:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L80)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please remove this comment.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 92 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METgjQR5stEEV6q-nTN:-METlg3J7rG_IDwPTq9h:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L92)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please add a period at the end of this sentence.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 109 at r1](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-METc-kMEarohbV8owyb:-METlj_26gxsqGV8pr9G:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ca262b3e301e8337628b8d1b856d7741fe2372e1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L109)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Instead of `HandshakerImpl`, can we call it `FakeS2AImpl`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-17 22:40 UTC, matthewstevenson88 requested changes
> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @davisgu and @matthewstevenson88)

___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 105 at r3](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MEy_4KeDvWvGn-VKGkN:-MEy_4KeDvWvGn-VKGkO:b-juvban) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/f784059036ca6a1e423bf47d60054dac1463baa2/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L105)):*
> ```Java
>     }
> 
>     private static class FakeS2AImpl extends S2AServiceGrpc.S2AServiceImplBase {
> ```

Please factor out the implementation of this class into a separate file and add unit tests for it.


<!-- Sent from Reviewable.io -->

2020-08-20 18:20 UTC, davisgu reviewed
> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @matthewstevenson88)

___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 105 at r3](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MEy_4KeDvWvGn-VKGkN:-MFC5SqjDar3KU7OSVn7:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/f784059036ca6a1e423bf47d60054dac1463baa2/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L105)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please factor out the implementation of this class into a separate file and add unit tests for it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-20 19:43 UTC, matthewstevenson88 requested changes
Thanks for the PR Davis! I've left comments below.

> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-:-MFCOWN4Aj_G4-XUGLT_:boso2lj)* status: 0 of 3 files reviewed, 21 unresolved discussions (waiting on @davisgu)

___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 42 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCBRZX-sqWlj8pa-Df:-MFCBRZX-sqWlj8pa-Dg:bcktubd) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L42)):*
> ```Java
> 
> /**
>  * Server that manages startup/shutdown of a fake handshaker service.
> ```

Please remove "Server that". (Javadoc comments should start with the verb.)
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 39 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCEXkh2aCRS9RGNIRa:-MFCEXkh2aCRS9RGNIRb:budj1o2) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L39)):*
> ```Java
>   private boolean assistingClient;
> 
>   public static final String grpcAppProtocol = "grpc";
> ```

For all static constants, please make their variables names full upper case, e.g. GRPC_APPLICATION_PROTOCOL.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 44 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCESBA7JDRSkXhHAkF:-MFCESBA7JDRSkXhHAkG:booup1v) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L44)):*
> ```Java
>   public static final String serverFrame = "ServerHelloAndFinished";
> 
>   private final String inKey  = "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk";
> ```

Please make these static constants.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 48 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCEKQw-tWnFg3AVVEG:-MFCEKQw-tWnFg3AVVEH:b9suirr) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L48)):*
> ```Java
> 
>   enum HandshakeState {
>   	INITIAL,
> ```

Please fix alignment.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 54 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCElrz2Vql_2Z3A34n:-MFCElrz2Vql_2Z3A34o:bm2u4bs) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L54)):*
> ```Java
>   }
> 
>   public FakeS2AImpl(){
> ```

Please don't use a public constructor - this is bad for extensibility, if we need to later to actual work in the constructor.

Instead, can you make the constructor private and add a static factory method that we can use to create a `FakeS2AImpl` instance?
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 55 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCElW27C5EYnFfL8Yb:-MFCEMfX4E33Em-BsWCl:b-wsh7of) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L55)):*
> ```Java
> 
>   public FakeS2AImpl(){
>   	this.state=HandshakeState.INITIAL;
> ```

Please fix alignment and spacing. You may have to run a linter or formatter.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 64 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCJIXzAF2Ege_38wfp:-MFCJIXzAF2Ege_38wfq:b-lm1lgu) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L64)):*
> ```Java
>       public void onNext(SessionReq req){
>         SessionResp resp = null;
>         if (req.getClientStart() != null){
> ```

Can we change this if-else if-else block to a switch statement?

You can do this using `req.getReqOneofCase()`, which will return an enum like CLIENT_START, SERVER_START, etc.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 71 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCIGFG7_ovaCYJleoF:-MFCIGFG7_ovaCYJleoG:bcxbpcl) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L71)):*
> ```Java
>           resp = processNext(req);
>         } else {
>           logger.log(Level.WARNING,"Session request has unexpected type: "+req.getClass());
> ```

Please lot this at "FINE" rather than at "WARNING".
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 78 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCKFfpANPO-b9VhsFE:-MFCKFfpANPO-b9VhsFF:b-x35k1x) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L78)):*
> ```Java
>       @Override
>       public void onError(Throwable t) {
>         logger.log(Level.WARNING, "Encountered error in routeChat", t);
> ```

Same here RE WARNING -> FINE.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 83 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCKDyBDYQ6CfanuGz7:-MFCKDyBDYQ6CfanuGz8:bd87lpg) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L83)):*
> ```Java
>       @Override
>       public void onCompleted() {
>         stream.onCompleted();
> ```

Please log that the stream is complete.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 86 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCKPz721FUUqr2yyGY:-MFCKPz721FUUqr2yyGZ:b-wom9lq) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L86)):*
> ```Java
>       }
> 
>       public SessionResp processClientStart(SessionReq req){
> ```

Does this need to be public? Can it be package-private only?

Also, please add a comment for the method.

Same with the other methods below.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 87 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCKKWd5VR-X3qk83Jz:-MFCKKWd5VR-X3qk83K-:byhqfan) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L87)):*
> ```Java
> 
>       public SessionResp processClientStart(SessionReq req){
>         SessionResp.Builder resp = SessionResp.newBuilder();
> ```

Please add `checkNotNull(req);` at the start of the method.

Same with the other methods below.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 99 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCKXWF4Nk_AZ0GHZPv:-MFCKXWF4Nk_AZ0GHZPw:byvmnv4) ([raw file](https://github.c [...]

2020-08-20 22:20 UTC, davisgu reviewed
> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4)* status: 0 of 3 files reviewed, 21 unresolved discussions (waiting on @davisgu and @matthewstevenson88)

___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java, line 42 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCBRZX-sqWlj8pa-Df:-MFCPeZ10IAmgzHYB15j:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeHandshaker.java#L42)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please remove "Server that". (Javadoc comments should start with the verb.)
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 39 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCEXkh2aCRS9RGNIRa:-MFCQQWc3KNVJJtgxLw3:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L39)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

For all static constants, please make their variables names full upper case, e.g. GRPC_APPLICATION_PROTOCOL.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 44 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCESBA7JDRSkXhHAkF:-MFCQRw6B85J1oAgu_fJ:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L44)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please make these static constants.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 48 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCEKQw-tWnFg3AVVEG:-MFCQVcd7-SAx8jKRstt:bs7wuo6) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L48)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please fix alignment.
</blockquote></details>

Done/.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 54 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCElrz2Vql_2Z3A34n:-MFCSRiR9HHhSpLZd_-h:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L54)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please don't use a public constructor - this is bad for extensibility, if we need to later to actual work in the constructor.

Instead, can you make the constructor private and add a static factory method that we can use to create a `FakeS2AImpl` instance?
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 55 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCElW27C5EYnFfL8Yb:-MFCSUl0-3pKj_omVDfs:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L55)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please fix alignment and spacing. You may have to run a linter or formatter.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 64 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCJIXzAF2Ege_38wfp:-MFCTJfM8Sn8K787Y5mp:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L64)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Can we change this if-else if-else block to a switch statement?

You can do this using `req.getReqOneofCase()`, which will return an enum like CLIENT_START, SERVER_START, etc.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 71 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCIGFG7_ovaCYJleoF:-MFCTMNYEuHVwNE4Nk0I:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L71)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please lot this at "FINE" rather than at "WARNING".
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 78 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCKFfpANPO-b9VhsFE:-MFCTOEV7YZoSSzydtCz:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L78)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Same here RE WARNING -> FINE.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 83 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCKDyBDYQ6CfanuGz7:-MFCTXacBO59Cub17RlF:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L83)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please log that the stream is complete.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 86 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCKPz721FUUqr2yyGY:-MFCTjju-iFZs8FqpcBz:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L86)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Does this need to be public? Can it be package-private only?

Also, please add a comment for the method.

Same with the other methods below.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 87 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCKKWd5VR-X3qk83Jz:-MFCUmC83pEswIv5i_hx:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L87)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please add `checkNotNull(req);` at the start of the method.

Same with the other methods below.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 99 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCKXWF4Nk_AZ0GHZPv:-MFCx46N9wSPdnJ9XmKK:b-896fix) ([raw file](https://github.com/matthewstevenson [...]

2020-08-20 22:59 UTC, davisgu reviewed
> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4)* status: 0 of 3 files reviewed, 21 unresolved discussions (waiting on @matthewstevenson88)

___
*[examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java, line 2 at r6](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFCNEKfBDNyprRkBRnA:-MFD5HKM3exOqQXGp583:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/8b743c735a325e61e3b015d8578964527061fdd1/examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java#L2)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Can we also test "process next" and "process resumption ticket"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-21 15:09 UTC, matthewstevenson88 requested changes
> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @davisgu)

___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 19 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGWbb1DjCugf6mhp6U:-MFGWTvS1picQKmq8YoN:bnc85gh) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L19)):*
> ```Java
> 
> import static com.google.common.base.Preconditions.checkNotNull;
> import com.google.net.grpc.s2a.handshaker.*;
> ```

Please import stuff from the proto individually.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 41 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGWl8H1Jkam61lWNP2:-MFGWl8H1Jkam61lWNP3:b-8e4hou) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L41)):*
> ```Java
> 
> 
>   public static final String GRPC_APP_PROTOCOL = "grpc";
> ```

Please use full words e.g. APP -> APPLICATION
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 60 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGWtQm5usvbOWWQ4aC:-MFGWtQn5IFVuGYrHbrB:b9x06p5) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L60)):*
> ```Java
>   }
> 
>   public static FakeS2AImpl create(){
> ```

Please add a comment for this.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 64 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGWyb-9MXV-lSBNWgu:-MFGWyb-9MXV-lSBNWgv:b6fwgoc) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L64)):*
> ```Java
>   }
> 
>   public void setState(HandshakeState s){
> ```

Just a thought: we could change the constructor from private to package-private, mark it as @VisibleForTesting, and pass in the initial state to the constructor?

(This is called "dependency injection", and it's the usual way of avoiding methods like this in Java.)
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 67 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGXh571uySvgvjJeET:-MFGXh571uySvgvjJeEU:b-56ty4z) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L67)):*
> ```Java
>     state = s;
>   }
> ```

Please add a comment for all public methods.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 88 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGXnmd1v-ke3x9aQnQ:-MFGXnmd1v-ke3x9aQnR:b-1cxm9d) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L88)):*
> ```Java
>             break;
>           default:
>             logger.log(Level.FINE,"Session request has unexpected type: "+req.getClass());
> ```

For Java logs, you usually add parameters like you do in C. For example, `"Session request has unexpected type: %s", req.getClass()`
___
*[examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java, line 41 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGYLQV8Ahf8_PvZwCi:-MFGYLQV8Ahf8_PvZwCj:bltm733) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java#L41)):*
> ```Java
> @RunWith(JUnit4.class)
> public class FakeS2AImplTest {
>   private StreamObserver<SessionResp> initRespStream;
> ```

If any variables can be null (e.g. `respLogger` and `error`), please mark them with the @Nullable annotation.
___
*[examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java, line 71 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGYuVu9kV-M0JQMPRc:-MFGYuVu9kV-M0JQMPRd:bnseab2) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java#L71)):*
> ```Java
>     setUpReq.onNext(emptyReq);
>     assertFalse(respLogger.getStatus().getCode() == Code.OK.value()); 
>     assertTrue(error==null);
> ```

Here and throughout: you can use `assertNull(error);`
___
*[examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java, line 103 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGZ4EB1Fo1V_Y__Axf:-MFGZ4EB1Fo1V_Y__Axg:bxw10d1) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java#L103)):*
> ```Java
> 
>   @Test 
>   public void processClientStart_pass()throws Exception{
> ```

Why is this called `pass`? Would `success` be a more appropriate term?


<!-- Sent from Reviewable.io -->

2020-08-21 18:04 UTC, davisgu reviewed
> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @matthewstevenson88 and @VisibleForTesting)

___
*[examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java, line 41 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGYLQV8Ahf8_PvZwCi:-MFGzSAkCh0XjpSgOvU8:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java#L41)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

If any variables can be null (e.g. `respLogger` and `error`), please mark them with the @Nullable annotation.
</blockquote></details>

Done.
___
*[examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java, line 71 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGYuVu9kV-M0JQMPRc:-MFGzfivBliKz5B167gK:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java#L71)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Here and throughout: you can use `assertNull(error);`
</blockquote></details>

Done.
___
*[examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java, line 103 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGZ4EB1Fo1V_Y__Axf:-MFGzlPb-Khonb_5az8u:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/test/java/io/grpc/examples/fakehandshaker/FakeS2AImplTest.java#L103)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Why is this called `pass`? Would `success` be a more appropriate term?
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 19 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGWbb1DjCugf6mhp6U:-MFH5Sht18jSnoWlykeX:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L19)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please import stuff from the proto individually.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 41 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGWl8H1Jkam61lWNP2:-MFGxz5D4K3VqHF_nPHK:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L41)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please use full words e.g. APP -> APPLICATION
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 60 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGWtQm5usvbOWWQ4aC:-MFGy4thDVko5nBcWXnO:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L60)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please add a comment for this.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 64 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGWyb-9MXV-lSBNWgu:-MFGygvj2U_Ad04jY1-f:b-g4b96z) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L64)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Just a thought: we could change the constructor from private to package-private, mark it as @VisibleForTesting, and pass in the initial state to the constructor?

(This is called "dependency injection", and it's the usual way of avoiding methods like this in Java.)
</blockquote></details>

Done (?). If i were to allow the constructor to accept a handshakestate, then that means I would not be able to initialize the FakeS2AImpl instance in the @before setup method in the tests, since I need to pass in a custom state for every test.-- compared to originally creating an instance in setup method, and then changing the state during the test.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 67 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGXh571uySvgvjJeET:-MFGznkSACfpOxGG24FE:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L67)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Please add a comment for all public methods.
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java, line 88 at r7](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFGXnmd1v-ke3x9aQnQ:-MFGz9sZAcM9d2Og3gjm:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/0e1ba8e33ea38dbb8a6871ccdad3b285365d2130/examples/example-tls/src/main/java/io/grpc/examples/fake-handshaker/FakeS2AImpl.java#L88)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

For Java logs, you usually add parameters like you do in C. For example, `"Session request has unexpected type: %s", req.getClass()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-21 18:47 UTC, matthewstevenson88 requested changes
> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @davisgu)

___
*[examples/example-tls/src/main/java/io/grpc/examples/fakehandshaker/FakeS2AImpl.java, line 76 at r8](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFHKbjR5ZWxubMkfJpg:-MFHKbjR5ZWxubMkfJph:b66sqt) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ff4f654a0f922f54e6c5424e5629de501cc97911/examples/example-tls/src/main/java/io/grpc/examples/fakehandshaker/FakeS2AImpl.java#L76)):*
> ```Java
>   }
> 
>   // Create a default FakeS2AImpl instance.
> ```

s/Create/Creates
___
*[examples/example-tls/src/main/java/io/grpc/examples/fakehandshaker/FakeS2AImpl.java, line 81 at r8](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFHL1cI8d4pPMbi9-QA:-MFHL1cI8d4pPMbi9-QB:b-5lprks) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ff4f654a0f922f54e6c5424e5629de501cc97911/examples/example-tls/src/main/java/io/grpc/examples/fakehandshaker/FakeS2AImpl.java#L81)):*
> ```Java
>   }
> 
>   // setUpSession sets up the S2A session. 
> ```

Remember all the comments above a function in Java should start with a verb, so this should be e.g. "Sets up ..."

Please change here and throughout


<!-- Sent from Reviewable.io -->

2020-08-21 19:03 UTC, davisgu reviewed
> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @matthewstevenson88)

___
*[examples/example-tls/src/main/java/io/grpc/examples/fakehandshaker/FakeS2AImpl.java, line 76 at r8](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFHKbjR5ZWxubMkfJpg:-MFHOYKT1hQZTjxLhoCg:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ff4f654a0f922f54e6c5424e5629de501cc97911/examples/example-tls/src/main/java/io/grpc/examples/fakehandshaker/FakeS2AImpl.java#L76)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

s/Create/Creates
</blockquote></details>

Done.
___
*[examples/example-tls/src/main/java/io/grpc/examples/fakehandshaker/FakeS2AImpl.java, line 81 at r8](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4#-MFHL1cI8d4pPMbi9-QA:-MFHOpR89ElsFhlqdTeQ:b-896fix) ([raw file](https://github.com/matthewstevenson88/grpc-java/blob/ff4f654a0f922f54e6c5424e5629de501cc97911/examples/example-tls/src/main/java/io/grpc/examples/fakehandshaker/FakeS2AImpl.java#L81)):*
<details><summary><i>Previously, matthewstevenson88 wrote…</i></summary><blockquote>

Remember all the comments above a function in Java should start with a verb, so this should be e.g. "Sets up ..."

Please change here and throughout
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-21 19:07 UTC, matthewstevenson88 approved these changes
> *[Reviewable](https://reviewable.io/reviews/matthewstevenson88/grpc-java/4)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-21 19:17 UTC, merged